apm-server:
  host: "0.0.0.0:8200" 

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"] 
  username: "elastic" 
  password: "StrongRandomPassword123!"

setup.kibana:
  host: "http://kibana:5601" 
