version: 3.0

dotenv: ["new.env"]

vars:
  DB_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"

tasks:
  docker-build:
    cmds:
      - docker-compose build

  docker-up:
    cmds:
      - docker-compose up -d

  docker-down:
    cmds:
      - docker-compose down

  docker-inspect-pg:
    cmds:
      - docker exec -it event_planner_postgres psql -U ${POSTGRES_USER} -d ${POSTGRES_DB}
    
  docker-inspect-redis:
    cmds:
      - docker exec -it event_planner_redis redis-cli

  migrate-up:
    cmds:
      - go run cmd/migrator/main.go -db "{{.DB_URL}}" -path "./migrations" -action up

  migrate-down:
    cmds:
      - go run cmd/migrator/main.go -db "{{.DB_URL}}" -path "./migrations" -action down

  run:
    cmds:
      - go run cmd/event-planner/main.go
